//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThingiBrowse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThingiBrowse.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThingiBrowse is an unofficial Open Source App which browses the Thingiverse website&apos;s digital designs for fabrication.
        ///
        ///Please note that I am not affiliated with Thingiverse or MakerBot® Industries in any way and that you should contact me at feedback.devorama.thingibrowse@googlemail.com if you have any problems with the App.
        ///
        ///Please rate this App if you like it..
        /// </summary>
        public static string info_text {
            get {
                return ResourceManager.GetString("info_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThingiBrowse is licensed under a Creative Commons 3.0 Attribution-NonCommercial-ShareAlike License by Mario Böhmer.
        ///
        ///You may obtain a copy of the License at http://creativecommons.org/licenses/by-nc-sa/3.0/.
        /// </summary>
        public static string license_text {
            get {
                return ResourceManager.GetString("license_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string license_title {
            get {
                return ResourceManager.GetString("license_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        public static string network_error_message {
            get {
                return ResourceManager.GetString("network_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error!.
        /// </summary>
        public static string network_error_title {
            get {
                return ResourceManager.GetString("network_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading Thing(s). Try again or try to update the app. Please send feedback if the error persists..
        /// </summary>
        public static string response_error_message {
            get {
                return ResourceManager.GetString("response_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string response_error_title {
            get {
                return ResourceManager.GetString("response_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find the project source at https://github.com/MarioBoehmer/ThingiBrowse.
        /// </summary>
        public static string source_text {
            get {
                return ResourceManager.GetString("source_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code:.
        /// </summary>
        public static string source_title {
            get {
                return ResourceManager.GetString("source_title", resourceCulture);
            }
        }
    }
}
